{% set name = "hdf5plugin" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 484250ec6e23ca12dc6812cba901fcefcc21b1c5ee6abd35bc56c121181aecc5

build:
  number: 0
  skip: true  # [win and py<30]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - hdf5
  run:
    - h5py
    - python

test:
  imports:
    - hdf5plugin

about:
  home: https://github.com/silx-kit/hdf5plugin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HDF5 Plugins for windows,MacOS and linux

extra:
  recipe-maintainers:
    - tschoonj
    - t20100
