{% set name = "hdf5plugin" %}
{% set version = "2.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 11da0aa6114ce20d98574f4c620dc1424b43e51ea5a219e2d203144f33c05193

build:
  number: 0
  skip: True  # [win and py<30]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - hdf5
  run:
    - h5py
    - python

test:
  imports:
    - hdf5plugin

about:
  home: "https://github.com/silx-kit/hdf5plugin"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "HDF5 Plugins for windows,MacOS and linux"

extra:
  recipe-maintainers:
    - tschoonj
    - t20100
